# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e20ab7aee42870b670e2d13e8956c10710b1b2059b0808871304ed03d3a915086c61d5b5e68893d43fc6bc2bea86894bd065015cf1a023bf0a6acd7e9350723e

test:
  secret_key_base: 5d47effa9a74d21b57cdb70f2d68f883d7bfb982b4d0b73fe2877181706708fc8420a862ccab046ca3b1897b5277e186b904dd203aacafee1ea7269a465643a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
